# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY Projeto01.sln ./
COPY src ./src
COPY tests ./tests

RUN dotnet restore

RUN dotnet publish src/Api -c Release -o /out --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out .

EXPOSE 5000
ENV ASPNETCORE_URLS "http://+:5000"

ENTRYPOINT ["dotnet", "Api.dll"]