services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projeto01
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.projeto01
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=projeto01;Username=postgres;Password=postgres"
      ASPNETCORE_URLS: http://+:80

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.projeto01
    ports:
      - "3000:3000"
    command: serve -s /app/frontend/dist -l 3000
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: "http://api:5000"

volumes:
  postgres_data:
